global:
  scrape_interval: 15s  # Інтервал збору метрик

scrape_configs:
  - job_name: 'php_app'
    static_configs:
      - targets: ['localhost:8080']  # Вказуємо на ваш PHP додаток

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Вказуємо на контейнер node_exporter
