version: '3.8'

services:
  app:
    build: .
    container_name: ecommerce-website-app  # Додано стабільне ім'я контейнера
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - prometheus
    networks:
      - mynetwork  # Додаємо мережу

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - mynetwork  # Додаємо мережу

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mynetwork  # Додаємо мережу

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - mynetwork  # Додаємо мережу

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - mynetwork  # Додаємо мережу

volumes:
  grafana_data:

networks:
  mynetwork:
    driver: bridge  # Створюємо віртуальну мережу для всіх контейнерів
